require("zaruun.plugins-setup")
require("zaruun.core.options")
require("zaruun.core.keymaps")
require("zaruun.core.colorscheme")
require("zaruun.plugins.comment")
-- require("zaruun.plugins.nvim-tree")
-- require("zaruun.plugins.lualine")
-- require("zaruun.plugins.telescope")
-- require("zaruun.plugins.nvim-cmp")
-- require("zaruun.plugins.lsp.mason")
-- require("zaruun.plugins.lsp.lspsaga")
-- require("zaruun.plugins.lsp.lspconfig")
-- require("zaruun.plugins.lsp.null-ls")
-- require("zaruun.plugins.autopairs")
-- require("zaruun.plugins.treesitter")
-- require("zaruun.plugins.gitsigns")
