- name: Check if LSD-rs is installed
  stat:
    path: "/home/{{ current_user.stdout }}/.local/bin/lsd"
  register: lsd_stats

- name: Install LSD-rs ( ls replacment )
  ansible.builtin.command: cargo install lsd
  when: lsd_stats.stat.exists == False

- name: Copy LSD-rs to /usr/bin/
  copy:
    src: "/home/{{ current_user.stdout }}/.cargo/bin/lsd"
    dest: "/home/{{ current_user.stdout }}/.local/bin/lsd"
  when: lsd_stats.stat.exists == False

- name: Clean up LSD-rs install files
  file:
    path: "/home/{{ current_user.stdout }}/.cargo/bin/lsd"
    state: absent
  when: lsd_stats.stat.exists == False