- name: Copy zsh config
  copy:
    src: ../dotfiles/zshrc/.zshrc
    dest: "/home/{{ current_user.stdout }}/."
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644
  tags:
  - zsh
  - scripts
  - dotfiles

- name: Copy nvim config
  copy:
    src: ../dotfiles/nvim
    dest: "/home/{{ current_user.stdout }}/.config/"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644
  tags:
  - nvim
  - dotfiles

- name: Copy tmux config
  copy:
    src: ../dotfiles/tmux/.tmux.conf
    dest: "/home/{{ current_user.stdout }}/"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644
  tags:
  - tmux
  - dotfiles

- name: Copy tmux config
  copy:
    src: ../dotfiles/alacritty
    dest: "/home/{{ current_user.stdout }}/.config/"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644
  tags:
  - dotfiles
  - alacritty