- name: Copy .zshrc
  copy:
    src: ../dotfiles/zshrc/.zshrc
    dest: "/home/{{ current_user.stdout }}/."
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644

- name: Copy nvim
  copy:
    src: ../dotfiles/nvim
    dest: "/home/{{ current_user.stdout }}/.config/"
    owner: "{{ current_user.stdout }}"
    group: "{{ current_user.stdout }}"
    mode: 0644