---
- name: Configure my personal development environment
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Retrieve current user
      command: whoami
      register: current_user
      tags:
      - nvim 
      - scripts
      - zsh
      - tmux

    - name: Update packages
      become: true
      apt:
        update_cache: yes
        upgrade: yes
      tags:
      - core

    - include: tasks/01-core-tools.yaml
    - include: tasks/02-oh-my-zsh.yaml  
    - include: tasks/03-nvim.yaml
    - include: tasks/04-nodejs.yaml
    - include: tasks/05-python.yaml
    - include: tasks/06-powershell.yaml
    - include: tasks/07-go.yaml
    - include: tasks/08-rust.yaml

    - include: tasks/998-copy-scripts.yaml
    - include: tasks/999-copy-dotfiles.yaml
    
